#include "native_test.h"

// Forward declarations of every test suite.
void run_pca_mapping();
void run_air_policy();
void run_air_ramp();
void run_midi_parser();
void run_event_queue();
void run_filter();
void run_keydriver_limits();
void run_calibration_migration();
void run_connection();
void run_instrument_notes();
void run_instrument_velocity_zero();
void run_instrument_cc7_zero();
void run_instrument_chord_and_loudest_release();
void run_instrument_sustain();
void run_instrument_all_notes_off();
void run_instrument_multichannel();
void run_instrument_precharge_nonblocking();
void run_instrument_transport_loss();
void run_instrument_geometry();
void run_air_module_end_to_end();
void run_composite_air();
void run_reservoir_regulator();
void run_composite_reservoir_requires_sensor();
void run_composite_runtime_reporting();
void run_safety_i2c_fault();
void run_safety_stuck_key();
void run_safety_comm_timeout();
void run_link_watchdog_long_note();
void run_link_watchdog_active_sensing();
void run_link_watchdog_reset();
void run_air_run_tracker();
void run_air_ramp_runtime();
void run_safety_pump_overrun();
void run_safety_air_unhealthy();
void run_safety_first_fault_wins();
void run_panic_input_fires_on_press();
void run_panic_input_debounce();
void run_panic_input_active_at_boot();
void run_config_schema_migration();
void run_config_record_header();
void run_validator_accepts_reference_board();
void run_validator_geometry();
void run_validator_pins();
void run_validator_air_and_sensor();
void run_validator_midi_and_safety();

int main() {
    RUN(run_pca_mapping);
    RUN(run_air_policy);
    RUN(run_air_ramp);
    RUN(run_midi_parser);
    RUN(run_event_queue);
    RUN(run_filter);
    RUN(run_keydriver_limits);
    RUN(run_calibration_migration);
    RUN(run_connection);
    RUN(run_instrument_notes);
    RUN(run_instrument_velocity_zero);
    RUN(run_instrument_cc7_zero);
    RUN(run_instrument_chord_and_loudest_release);
    RUN(run_instrument_sustain);
    RUN(run_instrument_all_notes_off);
    RUN(run_instrument_multichannel);
    RUN(run_instrument_precharge_nonblocking);
    RUN(run_instrument_transport_loss);
    RUN(run_instrument_geometry);
    RUN(run_air_module_end_to_end);
    RUN(run_composite_air);
    RUN(run_reservoir_regulator);
    RUN(run_composite_reservoir_requires_sensor);
    RUN(run_composite_runtime_reporting);
    RUN(run_safety_i2c_fault);
    RUN(run_safety_stuck_key);
    RUN(run_safety_comm_timeout);
    RUN(run_link_watchdog_long_note);
    RUN(run_link_watchdog_active_sensing);
    RUN(run_link_watchdog_reset);
    RUN(run_air_run_tracker);
    RUN(run_air_ramp_runtime);
    RUN(run_safety_pump_overrun);
    RUN(run_safety_air_unhealthy);
    RUN(run_safety_first_fault_wins);
    RUN(run_panic_input_fires_on_press);
    RUN(run_panic_input_debounce);
    RUN(run_panic_input_active_at_boot);
    RUN(run_config_schema_migration);
    RUN(run_config_record_header);
    RUN(run_validator_accepts_reference_board);
    RUN(run_validator_geometry);
    RUN(run_validator_pins);
    RUN(run_validator_air_and_sensor);
    RUN(run_validator_midi_and_safety);

    std::printf("\n%d checks, %d failures\n", nt::checks(), nt::failures());
    return nt::failures() == 0 ? 0 : 1;
}
